###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "akhena",
  "price": 444
}

###
GET http://localhost:3000/products
Content-Type: application/json

###
POST http://localhost:3000/order
Content-Type: application/json

{
  "name": "Aaa",
  "price": 91
}