###
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "joni",
  "password": "joni"
}

###
POST http://localhost:3000/api/v1/products
Content-Type: application/json
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJuYW1lIjoiam9uaSIsIm5hbWUiOiJKb25pIiwicm9sZXMiOlsiYWRtaW4iXX0sImlhdCI6MTY4NjMyMTkwMywiZXhwIjoxNjg2MzI1NTAzfQ.34V4v38JfFBwzDwv6F4fEFnMaVmlSSaEVef91akY6To

{
  "name": "apple",
  "price": 15000
}

###
GET http://localhost:3000/api/v1/products
Content-Type: application/json
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJuYW1lIjoiam9uaSIsIm5hbWUiOiJKb25pIiwicm9sZXMiOlsiYWRtaW4iXX0sImlhdCI6MTY4NjMyMTkwMywiZXhwIjoxNjg2MzI1NTAzfQ.34V4v38JfFBwzDwv6F4fEFnMaVmlSSaEVef91akY6To

###
POST http://localhost:3000/api/v1/order
Content-Type: application/json
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJuYW1lIjoiam9uaSIsIm5hbWUiOiJKb25pIiwicm9sZXMiOlsiYWRtaW4iXX0sImlhdCI6MTY4NjMyMTkwMywiZXhwIjoxNjg2MzI1NTAzfQ.34V4v38JfFBwzDwv6F4fEFnMaVmlSSaEVef91akY6To

{
  "name": "durian",
  "price": 90000
}

